import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ClipboardList, Eye, FileText, Mail, Calendar } from 'lucide-react';

interface InspectionTabProps {
  mainForm: any;
}

export const InspectionTab = ({ mainForm }: InspectionTabProps) => {
  const [showDocPreview, setShowDocPreview] = useState(false);
  const [showEmailPreview, setShowEmailPreview] = useState(false);
  const [inspectionData, setInspectionData] = useState({
    companyName: mainForm.companyName || '',
    clientDepartment: mainForm.clientDepartment || '',
    securityLevel: mainForm.securityLevel || '',
    orgSiteNumber: mainForm.orgSiteNumber || '',
    contractType: mainForm.contractType || '',
    contractNumber: mainForm.contractNumber || '',
    awardDate: '',
    expiryDate: ''
  });

  const generateDocPreview = () => {
    return `
INSPECTION REPORT

Company Information:
Name: ${inspectionData.companyName}
Client Department: ${inspectionData.clientDepartment}
Organization - Site Number: ${inspectionData.orgSiteNumber}

Contract Details:
Type: ${inspectionData.contractType}
Number: ${inspectionData.contractNumber}
Award Date: ${inspectionData.awardDate || '[Not specified]'}
Expiry Date: ${inspectionData.expiryDate || '[Not specified]'}

Security Information:
Security Level: ${inspectionData.securityLevel}
Activity Number: ${mainForm.activityNumber || '[Not specified]'}
Inspection Class: ${mainForm.inspectionClass || '[Not specified]'}
Inspection Date: ${mainForm.date || '[Not specified]'}

INSPECTION FINDINGS:
[This section will contain detailed inspection findings and recommendations]

CONCLUSION:
This inspection was conducted in accordance with the Government Security Policy and related directives for facilities security clearance assessments.

Inspector: [Inspector Name]
Date: ${new Date().toLocaleDateString()}
    `.trim();
  };

  const generateEmailPreview = () => {
    return `
Subject: Security Inspection Notification - ${inspectionData.companyName}

Dear Chief Security Officer,

This email serves as formal notification regarding the security inspection conducted for your organization.

INSPECTION DETAILS:
Activity Number: ${mainForm.activityNumber || '[Not specified]'}
Company: ${inspectionData.companyName}
Contract: ${inspectionData.contractType} - ${inspectionData.contractNumber}
Security Level: ${inspectionData.securityLevel}
Inspection Date: ${mainForm.date || '[Not specified]'}

The inspection has been completed and the formal report will be provided separately. Please ensure that any immediate security concerns identified during the inspection are addressed promptly.

If you have any questions regarding this inspection or require clarification on any findings, please do not hesitate to contact the undersigned.

Thank you for your cooperation during the inspection process.

Regards,

[Inspector Name]
Industrial Security Inspector
[Contact Information]

---
This is an automated notification generated by the Inspection Management System.
    `.trim();
  };

  return (
    <div className="p-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <ClipboardList className="h-5 w-5 text-primary" />
            <span>Inspection</span>
          </CardTitle>
          <CardDescription>
            Generate inspection reports and email notifications for 1F and 1G inspection classes.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="inspection-company">Company Name</Label>
                <Input
                  id="inspection-company"
                  value={inspectionData.companyName}
                  onChange={(e) => setInspectionData({ ...inspectionData, companyName: e.target.value })}
                  placeholder="Auto-populated from Main"
                  className="bg-muted"
                  readOnly
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="inspection-department">Client Department</Label>
                <Input
                  id="inspection-department"
                  value={inspectionData.clientDepartment}
                  onChange={(e) => setInspectionData({ ...inspectionData, clientDepartment: e.target.value })}
                  placeholder="Auto-populated from Main"
                  className="bg-muted"
                  readOnly
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="inspection-security">Security Level</Label>
                <Input
                  id="inspection-security"
                  value={inspectionData.securityLevel}
                  onChange={(e) => setInspectionData({ ...inspectionData, securityLevel: e.target.value })}
                  placeholder="Auto-populated from Main"
                  className="bg-muted"
                  readOnly
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="inspection-org">Organization - Site Number</Label>
                <Input
                  id="inspection-org"
                  value={inspectionData.orgSiteNumber}
                  onChange={(e) => setInspectionData({ ...inspectionData, orgSiteNumber: e.target.value })}
                  placeholder="Auto-populated from Main"
                  className="bg-muted"
                  readOnly
                />
              </div>
            </div>

            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="inspection-contract-type">Contract Type</Label>
                <Input
                  id="inspection-contract-type"
                  value={inspectionData.contractType}
                  onChange={(e) => setInspectionData({ ...inspectionData, contractType: e.target.value })}
                  placeholder="Auto-populated from Main"
                  className="bg-muted"
                  readOnly
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="inspection-contract-number">Contract Number</Label>
                <Input
                  id="inspection-contract-number"
                  value={inspectionData.contractNumber}
                  onChange={(e) => setInspectionData({ ...inspectionData, contractNumber: e.target.value })}
                  placeholder="Auto-populated from Main"
                  className="bg-muted"
                  readOnly
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="inspection-award-date" className="flex items-center space-x-2">
                  <Calendar className="h-4 w-4" />
                  <span>Award Date</span>
                </Label>
                <Input
                  id="inspection-award-date"
                  type="date"
                  value={inspectionData.awardDate}
                  onChange={(e) => setInspectionData({ ...inspectionData, awardDate: e.target.value })}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="inspection-expiry-date" className="flex items-center space-x-2">
                  <Calendar className="h-4 w-4" />
                  <span>Expiry Date</span>
                </Label>
                <Input
                  id="inspection-expiry-date"
                  type="date"
                  value={inspectionData.expiryDate}
                  onChange={(e) => setInspectionData({ ...inspectionData, expiryDate: e.target.value })}
                />
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="border-2 border-dashed border-border">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <FileText className="h-5 w-5" />
                    <span>Document Preview</span>
                  </div>
                  <Button 
                    variant="ghost" 
                    size="sm"
                    onClick={() => setShowDocPreview(!showDocPreview)}
                  >
                    <Eye className="h-4 w-4 mr-2" />
                    {showDocPreview ? 'Hide' : 'Show'}
                  </Button>
                </CardTitle>
              </CardHeader>
              <CardContent>
                {showDocPreview ? (
                  <div className="bg-muted/50 rounded-lg p-3 max-h-96 overflow-y-auto">
                    <pre className="text-xs whitespace-pre-wrap font-mono">{generateDocPreview()}</pre>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground">
                    Click "Show" to preview the inspection document with current field values.
                  </p>
                )}
              </CardContent>
            </Card>

            <Card className="border-2 border-dashed border-border">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <Mail className="h-5 w-5" />
                    <span>Email Preview</span>
                  </div>
                  <Button 
                    variant="ghost" 
                    size="sm"
                    onClick={() => setShowEmailPreview(!showEmailPreview)}
                  >
                    <Eye className="h-4 w-4 mr-2" />
                    {showEmailPreview ? 'Hide' : 'Show'}
                  </Button>
                </CardTitle>
              </CardHeader>
              <CardContent>
                {showEmailPreview ? (
                  <div className="bg-muted/50 rounded-lg p-3 max-h-96 overflow-y-auto">
                    <pre className="text-xs whitespace-pre-wrap font-mono">{generateEmailPreview()}</pre>
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground">
                    Click "Show" to preview the notification email that will be sent to the organization.
                  </p>
                )}
              </CardContent>
            </Card>
          </div>

          <div className="bg-muted/50 rounded-lg p-4">
            <h4 className="font-medium text-foreground mb-2">Auto-populated from Main:</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-muted-foreground">
              <div>
                <p>• Company Name: {mainForm.companyName || 'Not set'}</p>
                <p>• Client Department: {mainForm.clientDepartment || 'Not set'}</p>
                <p>• Security Level: {mainForm.securityLevel || 'Not set'}</p>
                <p>• Org-Site Number: {mainForm.orgSiteNumber || 'Not set'}</p>
              </div>
              <div>
                <p>• Contract Type: {mainForm.contractType || 'Not set'}</p>
                <p>• Contract Number: {mainForm.contractNumber || 'Not set'}</p>
                <p>• Activity Number: {mainForm.activityNumber || 'Not set'}</p>
                <p>• Inspection Class: {mainForm.inspectionClass || 'Not set'}</p>
              </div>
            </div>
          </div>

          <div className="pt-4 border-t space-y-3">
            <Button className="w-full">
              <FileText className="h-4 w-4 mr-2" />
              Generate Inspection Report (DOCX + PDF)
            </Button>
            <Button variant="outline" className="w-full">
              <Mail className="h-4 w-4 mr-2" />
              Generate Email Draft (.eml)
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};