export const SECURITY_PRODUCTS = {
  'TPM': [
    'TPM 1.2',
    'TPM 2.0',
    'fTPM (Firmware TPM)',
    'PTT (Platform Trust Technology)',
    'Other'
  ],
  'Secure Boot': [
    'UEFI Secure Boot Enabled',
    'Legacy BIOS (No Secure Boot)',
    'Other'
  ],
  'BitLocker/Encryption': [
    'BitLocker (Windows)',
    'FileVault (macOS)',
    'LUKS (Linux)',
    'VeraCrypt',
    'DiskCryptor',
    'PGP Whole Disk Encryption',
    'McAfee Complete Data Protection',
    'Sophos SafeGuard',
    'Symantec Endpoint Encryption',
    'Other'
  ],
  'Antivirus': [
    'Windows Defender',
    'McAfee Endpoint Security',
    'Norton Security',
    'Symantec Endpoint Protection',
    'Trend Micro',
    'Kaspersky',
    'Bitdefender',
    'ESET NOD32',
    'Sophos',
    'CrowdStrike Falcon',
    'Carbon Black',
    'SentinelOne',
    'Webroot',
    'Avast Business',
    'AVG Business',
    'F-Secure',
    'Panda Security',
    'A-Squared Anti-Malware',
    'AhnLab',
    'Aura Antivirus',
    'Avira',
    'Bkav',
    'Clam AntiVirus',
    'Cynet 360',
    'Dr. Web',
    'G Data Antivirus',
    'K7 Computing',
    'Malwarebytes',
    'Powertech Antivirus',
    'Quick Heal',
    'Surfshark Antivirus',
    'Systweak Antivirus',
    'TotalAV',
    'Trellix Endpoint Security',
    'VIPRE Antivirus',
    'Other'
  ],
  'Firewall': [
    'Windows Defender Firewall',
    'pfSense',
    'Fortinet FortiGate',
    'Cisco ASA',
    'Palo Alto Networks',
    'SonicWall',
    'Sophos XG Firewall',
    'Check Point',
    'WatchGuard',
    'Barracuda',
    'Juniper Networks',
    'Hardware-based (Managed by Network Team)',
    'Other'
  ],
  'VPN': [
    'Cisco AnyConnect',
    'Palo Alto GlobalProtect',
    'Fortinet FortiClient',
    'OpenVPN',
    'WireGuard',
    'Pulse Secure',
    'SonicWall NetExtender',
    'Check Point Mobile',
    'Windows Built-in VPN',
    'NordVPN',
    'NordVPN Teams',
    'NordLayer',
    'Surfshark',
    'ExpressVPN',
    'Proton VPN',
    'Private Internet Access (PIA)',
    'CyberGhost VPN',
    'IPVanish',
    'Mullvad VPN',
    'Windscribe',
    'TunnelBear',
    'Hotspot Shield',
    'PureVPN',
    'Hide.me VPN',
    'VyprVPN',
    'HMA (HideMyAss!)',
    'PrivadoVPN',
    'TorGuard VPN',
    'Astrill VPN',
    'Norton Secure VPN',
    'McAfee Mobile Security',
    'GOOSE VPN',
    'Ivanti Connect Secure',
    'Perimeter 81',
    'Access Server',
    'GoodAccess',
    'UTunnel VPN',
    'Secomea',
    'Pritunl',
    'Other'
  ],
  'Password Protection': [
    'Windows Hello',
    'BitLocker PIN',
    'BIOS/UEFI Password',
    'Local Account Password',
    'Domain-managed (Active Directory)',
    'Azure AD / MS Entra ID',
    'Multi-factor Authentication (MFA)',
    'Okta',
    'Duo Security',
    '1Password',
    'Bitwarden',
    'Dashlane',
    'Keeper Password Manager',
    'LastPass',
    'NordPass',
    'Proton Pass',
    'KeePass',
    'RoboForm',
    'Sticky Password',
    'LogMeOnce Password Manager',
    'Zoho Vault',
    'Enpass',
    'Norton Password Manager',
    'Avira Password Manager',
    'Total Password',
    'CyberArk PAM',
    'ManageEngine Password Manager Pro',
    'Securden',
    'Secret Server Password Manager',
    'SailPoint Password Management',
    'OneLogin',
    'ManageEngine ADSelfService Plus',
    'FastPass SSPR',
    'AxCrypt',
    'Folder Lock',
    'Other'
  ],
  'Biometric Auth': [
    'Fingerprint Scanner',
    'Facial Recognition (Windows Hello)',
    'Iris Scanner',
    'Smart Card Reader',
    'FIDO2 Security Key',
    'YubiKey',
    'Other'
  ]
} as const;

export const SECURITY_CATEGORIES = Object.keys(SECURITY_PRODUCTS) as Array<keyof typeof SECURITY_PRODUCTS>;
