// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejctzcsegswfrkwbywte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqY3R6Y3NlZ3N3ZnJrd2J5d3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Mjk1NDMsImV4cCI6MjA3NDMwNTU0M30.lu-xf1W72mRfCdGyUDTrcohJKkRxoWEzJZv0toZ5qWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});